# specify a directory to install
cask_args appdir: '/Applications'
tap 'caskroom/homebrew-cask' || true

brew 'awscli'
brew 'azure-cli'
brew 'docker'
brew 'git'
brew 'golang'
brew 'jq'
brew 'node'
brew 'nomad'
brew 'python'
brew 'rsync'
brew 'ruby'
brew 'sonar-scanner'
brew 'terraform'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'wget'

cask 'atom'
cask 'chefdk'
cask 'docker-toolbox'
cask 'google-chrome'
cask 'java'
cask 'lastpass'
cask 'postman'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'skype'
cask 'slack'
cask 'suspicious-package'
cask 'vagrant'
cask 'virtualbox'
